name: Build Save

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build savedata
        run: |
          cd save-gen
          python3 make_save.py -w "github-actions"

      - name: Rename output
        run: cp save-gen/build_dst/savedata_meta.dat save-gen/build_dst/savedata.dat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: savedata
          path: save-gen/build_dst/savedata.dat
